### ISSUE TITLE
Unable to activate interface

### ISSUE THREAD

**Issue by evilthreads669966** [sdaubert/packetgen#120]
```unable to activate interface: -8, wlp0s20f``` is the error message. I'm running the script as root. The name i pass for the interface is the name that shows up when I run ```ifconfig```. I've installed libpcap-dev and the gem.

**Comment by sdaubert** [comment]
Hi @evilthreads669966. Usually, error -8 is about permissions : you have to be root to use packet injection and/or capture. Next, check your interface is up. If not : `ip link set wlp0s20f up`

**Comment by evilthreads669966** [comment]
Thanks. I was worried that it had something to do with linux.
