### ISSUE TITLE
Make specifying an interface optional.

### ISSUE THREAD

**Issue by picatz** [sdaubert/packetgen#34]
# Thoughts

When working with PacketFu, I'm able to start capturing packets without needing to specify the interface to use because that is optionally figured out for me if I don't pass in that argument.

For PacketGen, I'm forced to specify the interface to listen on as the first argument. I think this should be moved to the second, optional hash that can be passed in optionally. I think we should put that interface specification as an option and make capturing that much simpler.

# Results

### Turn This

```ruby
require 'packetgen'

PacketGen.capture('en0') do |packet|
  #do_stuffs_with_packet
end
```

### Into This

```ruby
require 'packetgen'

PacketGen.capture(iface: 'en0') do |packet|
  #do_stuffs_with_packet
end
```

And this:

```ruby
require 'packetgen'

PacketGen.capture do |packet|
  #do_stuffs_with_packet
end
```

And this:

```ruby
require 'packetgen'

PacketGen.capture(iface: 'en0', max: 2) do |packet|
  #do_stuffs_with_packet
end
```

## How?

We ( basically ) just need to use Pcaprub's interface lookup to achieve this by changing the set_options method for PacketGen::Capture:

```ruby
def set_options(options)
      @max = options[:max] if options[:max]
      @filter = options[:filter] if options[:filter]
      @timeout = options[:timeout] if options[:timeout]
      if options[:promisc]
        @promisc = options[:promisc]
      else
        @promisc ||= false
      end
      if options[:snaplen]
        @snaplen = options[:snaplen]
      else
        @snaplen ||= DEFAULT_SNAPLEN
      end
      if options[:parse].nil?
        @parse = true if @parse.nil?
      else
        @parse = options[:parse]
      end
      if options[:iface]
        @iface = options[:iface] 
      else
        @iface = Pcap.lookupdev
      end
    end
```

## My Implementation
[I've implemented this to work](https://github.com/picatz/packetgen/tree/no-iface-required); but I'm having problems with some of the specs where I'm getting errors like these ( which probably has nothing to do with interface specification, I'd think, I dunno ):
![screen shot](https://cloud.githubusercontent.com/assets/14850816/21958651/1f475ec4-da81-11e6-926b-9122fe3eb24d.png)

I can make the pull request, otherwise if you want to implement it yourself, it's not too bad -- but requires some changes to the tests obviously to reflect the interface specification as a part of the main hash.

![shrug](https://cloud.githubusercontent.com/assets/14850816/21958682/e9ca51b0-da81-11e6-8f9a-fe742a972241.gif)

**Comment by sdaubert** [comment]
@picatz Thanks for you proposal. Please make a PR. I will investigate this issue.

**Comment by picatz** [comment]
OK NOW I'M ACTUALLY GOING TO MAKE THAT PR THIS WEEKEND.
