### ISSUE TITLE
pgconsole on macos/osx error

### ISSUE THREAD

**Issue by picatz** [sdaubert/packetgen#41]
```
$ pgconsole 
/usr/local/lib/ruby/gems/2.4.0/gems/packetgen-1.4.1/lib/packetgen/config.rb:34:in `initialize': uninitialized constant Socket::AF_PACKET (NameError)
Did you mean?  Socket::AF_CNT
	from /usr/local/lib/ruby/gems/2.4.0/gems/packetgen-1.4.1/bin/pgconsole:26:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/packetgen-1.4.1/bin/pgconsole:26:in `<top (required)>'
	from /usr/local/bin/pgconsole:22:in `load'
	from /usr/local/bin/pgconsole:22:in `<main>'
[ ╯ '□']╯︵┻━┻)
```

The config for pgconsole doesn't seem to be compatible with osx/macos.

### Side Note

You're the best. There's no serious need for me to have this right now, but, I figured I'd let ya' know.

Maybe I can figure it out and make a PR.

**Comment by sdaubert** [comment]
@picatz I don't known OS X. AF_PACKET is used to get MAC address from an array returned by  `NetworkInterface.addresses`. Is there no Ethernet on OS X ?

**Comment by picatz** [comment]
I was also relatively confused last night when I made the issue.

However, upon some google'n I seem to have found the Socket constant I want to work with on OSX. 

## Socket
### AF_LINK
Link layer interface. Works on osx, and macos stuff.
### AF_PACKET
Direct link-layer access. Works on linux.
#### Example
```ruby
[1] pry(main)> require 'socket'
=> true
[2] pry(main)> Socket::AF_LINK # works on macos
=> 18
[3] pry(main)> Socket::AF_PACKET # no dice!
NameError: uninitialized constant Socket::AF_PACKET
Did you mean?  Socket::AF_CNT
from (pry):3:in `__pry__'
```

## How to Fix

Maybe some sort of method to get the mac address if the other way fails, or a platform check?

```ruby
def mac_addr
  begin
    Socket::AF_PACKET # linux
  rescue
    Socket::AF_LINK # macos
  end
end

```

**Comment by sdaubert** [comment]
I've made a fix on branch `issue41`. Plesase, could you test it?

**Comment by picatz** [comment]
The mac address checking worked! But, funny enough, the iface was also not being set properly!

I made a pull request https://github.com/sdaubert/packetgen/pull/42 that works for me.

**Comment by sdaubert** [comment]
As said [here](https://github.com/sdaubert/packetgen/pull/42/files#r108620016), I cannot accept #42 for now. I have modified current PR to add OS X's loopback interface detection. Does it suit you?

**Comment by picatz** [comment]
Ah, I see. So I can see that it's now catching my `lo0` loopback by default now. 

But, I don't think this really gives me the desired results I'd want for the shell, right? Assumably, it would just load up and be read to rock and roll with my `en0` ( my default ) interface when I pull up `pgconsole`.

In the original code, wasn't it looking originally for the first interface that wasn't `lo`? So, wouldn't we want, like, the opposite of the match at first? Then, if that's gone horribly wrong, we use loopback as the default?

**Comment by sdaubert** [comment]
@picatz good point, we don't want to use a loopback interface in the shell.

**Comment by sdaubert** [comment]
@picatz My last proposal is not good. Forget it...

**Comment by picatz** [comment]
@sdaubert Hopefully I did this right: https://github.com/sdaubert/packetgen/pull/42/commits/efa5adcba43b6fac02797189f7e7b970edd66dbb

Did the editing on the github website. Haven't done that before. So, I dunno. But, yeah. Works on my end! 😂

**Comment by picatz** [comment]
Also, I realized I have my debug line still in the pgconsole in those commits.

😅  Should that be removed?

**Comment by sdaubert** [comment]
@picatz yes, you can remove it by making a new commit ;-)

**Comment by picatz** [comment]
Removed it: https://github.com/sdaubert/packetgen/pull/42/commits/34f7a498de268a21fe981f66548828307bdcbd91
