### ISSUE TITLE
Read .pcap formatted files

### ISSUE THREAD

**Issue by picatz** [sdaubert/packetgen#44]
Sometimes I want to use PacketGen to work with packet captures that may not be in `.pcapng` format. For example, if I dumped stuff with tcpdump and then wanted to work with that capture with packetgen later, it's not exactly straight forward.

Under the hood, I think we could pretty easily have the `.read()` method work with both .pcap and .pcapng files by using PCAPRUB's `.open_offline()` method.

## No Worky

```ruby
pcap = PacketGen.read('example.pcap')
```

## How open_offline works

```ruby
packets = PCAPRUB::Pcap.open_offline('example.pcap')
```

#### How I've Been Using It

Here's basically how I've been getting around not being able to just use `.read()`, because I need to:

```ruby
parsed_packets = []
PCAPRUB::Pcap.open_offline('example.pcap').each_packet do |packet|
  parsed_packets << PacketGen.parse(packet.to_s)
end
parsed_packets
```

## Proposal

```ruby
# Read packets from +filename+.
#
# @see {PcapNG::File} for more on reading pcapng files.
# @param [String] filename PcapNG or Pcap file
# @return [Array<Packet>]
def self.read(filename)
  extension = File.extname(filename).downcase
  if extension == ".pcap"
    # read pcap via PCAPRUB::Pcap.open_offline in some fashion
    # honestly I haven't figured out the best way yet
    # but, ya' know
  elsif extension == ".pcapng"
    PcapNG::File.new.read_packets filename
  else
    # error, extension be a lie OR:
    # check for them, automagically read both even if the filename was kittens
  end
end
```

Thoughts on this?

**Comment by sdaubert** [comment]
@picatz This is a great proposal. In `else` part, I would try to a read a pcapng first, and on exception, thren read a pcap. What do you think about?
Could you propose a PR?

**Comment by picatz** [comment]
I can put together a PR fo'shizzle ma' bizzle.

**Comment by picatz** [comment]
Totes gunna do this soon. Promise.

**Comment by picatz** [comment]
@sdaubert Finally did a thing. https://github.com/sdaubert/packetgen/pull/45

**Comment by sdaubert** [comment]
#45 was merged

**Comment by sdaubert** [comment]
also did a new gem (v1.4.3)
