### ISSUE TITLE
Capture Timeout

### ISSUE THREAD

**Issue by picatz** [sdaubert/packetgen#52]
## The Issue
For the [`.start`](https://github.com/sdaubert/packetgen/blob/master/lib/packetgen/capture.rb#L83) method when using the `Capture` class, a [`@pcap`](https://github.com/sdaubert/packetgen/blob/master/lib/packetgen/capture.rb#L85) instance variable is created using PCAPRUB's [`open_live`](https://github.com/pcaprub/pcaprub/blob/340c88d05cea29ee6d711563264bd2f5a2a4878c/ext/pcaprub_c/pcaprub.c#L555) method. The very last argument for the `.open_live` method when using the `.start` method is `1`. However, I'd assume this should be the [`@timeout`](https://github.com/sdaubert/packetgen/blob/master/lib/packetgen/capture.rb#L117) instance variable that is set in the [`set_options`](https://github.com/sdaubert/packetgen/blob/master/lib/packetgen/capture.rb#L114) method. Within the `Capture` class's [`initialize`](https://github.com/sdaubert/packetgen/blob/master/lib/packetgen/capture.rb#L54) method a default for the `@timeout` variable could be set to 1 when users don't provide anything, while also allowing them to actually change it for their capture needs.

Hope that makes sense. I'm going to make a PR to fix this. 👍

**Comment by picatz** [comment]
## Made Pull Request
My PR has been submitted: https://github.com/sdaubert/packetgen/pull/53

**Comment by sdaubert** [comment]
From pcap_open_live(3PCAP):

> pcap_t *pcap_open_live(const char *device, int snaplen, int promisc, int to_ms, char *errbuf);
>
>to_ms specifies the read timeout in milliseconds.

But, with a value of 1, this method never returns. This is why timeout is managed through a thread.
Perhaps PCAPRUB handles this value differently than said in C library manual page

**Comment by picatz** [comment]
More likely the case I was was misunderstanding how the timeout was being used. 🤣
