### ISSUE TITLE
Gem install runtime error

### ISSUE THREAD

**Issue by Beyarz** [sdaubert/packetgen#54]
ProNoScope2:~ bayar.nahro$ gem install packetgen
Building native extensions.  This could take a while...
ERROR:  Error installing packetgen:
        ERROR: Failed to build gem native extension.

    current directory: /Users/bayar.nahro/.rvm/gems/ruby-2.4.2/gems/pcaprub-0.12.4/ext/pcaprub_c
/Users/bayar.nahro/.rvm/rubies/ruby-2.4.2/bin/ruby -r ./siteconf20171014-32877-1wibpka.rb extconf.rb

[*] Running checks for pcaprub_c code...
platform is x86_64-darwin15
checking for ruby/thread.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/Users/bayar.nahro/.rvm/rubies/ruby-2.4.2/bin/$(RUBY_BASE_NAME)
        --with-pcap-dir
        --without-pcap-dir
        --with-pcap-include
        --without-pcap-include=${pcap-dir}/include
        --with-pcap-lib
        --without-pcap-lib=${pcap-dir}/lib
/Users/bayar.nahro/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /Users/bayar.nahro/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/mkmf.rb:588:in `try_cpp'
        from /Users/bayar.nahro/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/mkmf.rb:1095:in `block in have_header'
        from /Users/bayar.nahro/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/mkmf.rb:945:in `block in checking_for'
        from /Users/bayar.nahro/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /Users/bayar.nahro/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from /Users/bayar.nahro/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
        from /Users/bayar.nahro/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from /Users/bayar.nahro/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
        from /Users/bayar.nahro/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/mkmf.rb:944:in `checking_for'
        from /Users/bayar.nahro/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/mkmf.rb:1094:in `have_header'
        from extconf.rb:74:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/bayar.nahro/.rvm/gems/ruby-2.4.2/extensions/x86_64-darwin-15/2.4.0/pcaprub-0.12.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/bayar.nahro/.rvm/gems/ruby-2.4.2/gems/pcaprub-0.12.4 for inspection.
Results logged to /Users/bayar.nahro/.rvm/gems/ruby-2.4.2/extensions/x86_64-darwin-15/2.4.0/pcaprub-0.12.4/gem_make.out

ProNoScope2:~ bayar.nahro$ cat /Users/bayar.nahro/.rvm/gems/ruby-2.4.2/extensions/x86_64-darwin-15/2.4.0/pcaprub-0.12.4/mkmf.log
"gcc -o conftest -I/Users/bayar.nahro/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/x86_64-darwin15 -I/Users/bayar.nahro/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/backward -I/Users/bayar.nahro/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0 -I. -I/opt/local/include -I/usr/local/include -I/Users/bayar.nahro/.rvm/rubies/ruby-2.4.2/include -I/usr/include  -I/usr/local/opt/libyaml/include -I/usr/local/opt/readline/include -I/usr/local/opt/libksba/include -I/usr/local/opt/openssl@1.1/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautological-compare -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wshorten-64-to-32 -Wimplicit-function-declaration -Wdivision-by-zero -Wdeprecated-declarations -Wextra-tokens  -fno-common -pipe conftest.c  -L. -L/Users/bayar.nahro/.rvm/rubies/ruby-2.4.2/lib -L/opt/local/lib -L/usr/local/lib -L/Users/bayar.nahro/.rvm/rubies/ruby-2.4.2/lib -L/usr/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl@1.1/lib -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl@1.1/lib     -lruby.2.4.2  -lpthread -ldl -lobjc "
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

My gem & ruby is up to date and I can't find any solution to this error.

**Comment by sdaubert** [comment]
This problem is related to pacprub gem, a dependency of packetgen.

I don't know OS X, but after googling a little:
```
xcode-select --install
```
For more info: https://www.google.com/search?dcr=0&q=xcrun%3A+error%3A+invalid+active+developer+path
