### ISSUE TITLE
cannot send a Dot11 packet

### ISSUE THREAD

**Issue by sdaubert** [sdaubert/packetgen#56]
From #55:

```ruby
pkt = PacketGen.gen('Dot11::Management', mac1: client, mac2: bssid, mac3: bssid)
pkt.add('Dot11::DeAuth', reason: 7)
pkt.calc

pkt.to_w('wlan0')
```

Nothing is sent

**Comment by sdaubert** [comment]
@KINGSABRI I did a test:
```ruby
bssid = '68:69:70:71:72:73'
pkt = PacketGen.gen('Dot11::Management', mac1: 'ff:ff:ff:ff:ff:ff', mac2: bssid, mac3: bssid)
pkt.add('Dot11::Beacon', interval: 0x600, cap: 0x401)
pkt.dot11_beacon.add_element(type: 'SSID', value: 'This is A fake SSID')
pkt.calc
pkt.to_w('wlan0')
```

I did a capture with wireshark (`-y` needed to force dot11, else all frames were captures as ethernet frames):
```
wireshark -i wlan0 -I -y IEEE802_11_RADIO -k
```
This packet is captured by wireshark, without error. There is a limit on this test: wireshark is run on same PC as packet emitter.

**Comment by KINGSABRI** [comment]
packets sent but still getting malformed packet

![image](https://user-images.githubusercontent.com/1071827/32254918-27fba5a2-beb5-11e7-99e6-97e95fc5eadd.png)

So no AP has shown when searching for new wifi networks

**Comment by KINGSABRI** [comment]
Can we add an argument to `#to_w` to how the number of times to send and interval? instead of writing a loop
eg.
```ruby
pkt.to_w('mon0', count: 10000, interval: 0.2)
```

**Comment by KINGSABRI** [comment]
Another good news is, DeAuth is working as well

```ruby
# pkt = PacketGen.gen('RadioTap').add('Dot11::Management', type: 0, subtype: 12, mac1: client, mac2: bssid, mac3: bssid).add('Dot11::DeAuth', reason: 7)
pkt = PacketGen.gen('RadioTap').add('Dot11::Management', mac1: client, mac2: bssid, mac3: bssid).add('Dot11::DeAuth', reason: 7)
pkt.calc

count.times do
  pkt.to_w(iface)
  puts 'Deauth sent via: ' + iface + ' to BSSID: ' + bssid + ' for Client: ' + client
end
```

**Comment by sdaubert** [comment]
@KINGSABRI about malformed packet: PacketGen always sets a FCS. To make my packet acceptable by wireshark, i had to check 'Assume packets have FCS' in Protocol Preferences.

Sending without RadioTap header:
![capture du 2017-11-01 10-27-46](https://user-images.githubusercontent.com/964388/32268440-5da70af4-beef-11e7-93bb-d5d08693bc85.png)

RadioTap header is marked as invalid in wireshark, but all others layers are OK.

**Comment by KINGSABRI** [comment]
>  i had to check 'Assume packets have FCS' in Protocol Preferences.
I see

> RadioTap header is marked as invalid in wireshark, but all others layers are OK.
Did you see the fake AP? because without RadioTap, I could not see it

**Comment by sdaubert** [comment]
I tried with a RadioTap header, and I have same result (without invalid RadioTap).

To conclude, i think I need another wifi receiver with wireshark.

**Comment by sdaubert** [comment]
@KINGSABRI no, as i have no other wifi receiver to check AP.

**Comment by KINGSABRI** [comment]
I'm using 
Alfa and I put it in monitoring mode 

>no, as i have no other wifi receiver to check AP.
your mobile is more than enough

**Comment by sdaubert** [comment]
I already tried with my mobile, but I saw no SSID, with and without RadioTap header.

**Comment by KINGSABRI** [comment]
> https://phishme.webex.com/meet/husam.omarphishme.com

Maybe putting the interface in monitoring mode is needed?

**Comment by sdaubert** [comment]
@KINGSABRI By adding a Rates element, i can reproduce it: with RadioTap, my mobile phone see beacon frames, but without it, SSID is not detected.

Need of RadioTap header to send Dot11 packet on the air is added in wiki. Will be added in Dot11 documentation too.

**Comment by picatz** [comment]
@KINGSABRI + @sdaubert : This is was an *awesome* issue to follow! I can't wait to try out ya'lls findings and build some wifi-hacking tools with ruby! 👏  

Ya'll the best. 🙇
