### ISSUE TITLE
Contributing to wiki

### ISSUE THREAD

**Issue by KINGSABRI** [sdaubert/packetgen#57]
There is no real  easy way to contribute to wiki 
here is my initial proposal 
https://github.com/KINGSABRI/packetgen-wiki/tree/master

**Comment by sdaubert** [comment]
That's a great start!

As for me, I was thinking about `Getting started`, which is in your proposal.

About wiki contribution, there seems to be only one solution: patches by email 😢

**Comment by KINGSABRI** [comment]
no problem for me, give me your email I'll send you my work once I've some

**Comment by KINGSABRI** [comment]
Ok another idea instead of the email is, great a new repository name it PacketGen-Wiki 
and we can contribute to it, then you can copy these changes by yourself to the main wiki

**Comment by sdaubert** [comment]
Yes, I saw that yesterday while i'm googling. I think this repo will ease contribution to wiki. I'll do that this evening.

**Comment by sdaubert** [comment]
Here it is: https://github.com/sdaubert/packetgen-wiki
