### ISSUE TITLE
Add FTP headers

### ISSUE THREAD

**Issue by KINGSABRI** [sdaubert/packetgen#62]

**Comment by sdaubert** [comment]
I had a look at FTP RFC:
* Commands are text-based. PacketGen is not well suited for this kind of protocol.
* This protocol is very (too?) complex.

This protocol will not be supported by PacketGen.

**Comment by picatz** [comment]
@sdaubert I totally respect your choice not not implement this! 

But, specifically, if you don't mind explaining it for me a bit more in depth: what's the complex part about the FTP protocol?

> **Note:** I've yet to really dig into the RFC myself, but I plan on it! 

**I don't want to waste your time.** So I don't mind just doing it for my own learning if you don't ever want it in the main branch. But, I'm sort of _perhaps genuinely naively_ thinking it could be cool to try to implement.

**Comment by sdaubert** [comment]
@picatz Feel free to try. If your implementation comes with specs and a good coverage, it will be merged.
But I have no time for this. So, you should have less support (from me) than you had for HTTP implementation.

**Comment by picatz** [comment]
@sdaubert No worries. We'll see if I end up being able to implement this. 😹

**Comment by sdaubert** [comment]
No news in almost 3 years. Close it.
