### ISSUE TITLE
make #recalc within #to_w

### ISSUE THREAD

**Issue by KINGSABRI** [sdaubert/packetgen#63]
Hello there, the title says it all
Why do we need to call `recalc` manually? 
we can make it called by default or add it as an option to `to_w` in case someone want to send it without calculation(no idea when someone needs that) to be something like

```ruby
pkt.to_w(iface, recalc: false)
```

Also, I hope we can add number of packets to be sent 

```ruby
pkt.to_w(iface, interval: 1000)
```

**Comment by sdaubert** [comment]
#calc should be done manually to allow sending erroneous packets on network. This is used, by example, to test or stress network devices.

I may add `recalc` option to  `#to_w`, but its default value will be `false` to keep compatibility.

About number of packet : OK, but we need the number of packet to send and an interval between them (with a default value for the latter)

**Comment by KINGSABRI** [comment]
> I may add recalc option to #to_w, but its default value will be false to keep compatibility.
Agreed, that's a good solution 

> About number of packet : OK, but we need the number of packet to send and an interval between them (with a default value for the latter)
defaults: number of packet: 1, interval: 0
