### ISSUE TITLE
SMBv1/2/3

### ISSUE THREAD

**Issue by KINGSABRI** [sdaubert/packetgen#74]
This great gem messes SMB protocol

**Comment by picatz** [comment]
SMB would be an awesome addition 👍

**Comment by sdaubert** [comment]
Yes, I think so :smile: 
I will look at it.

**Comment by sdaubert** [comment]
From my readings, there really are only 2 versions of the protocol (ie from packet format view):
* CIFS/SMBv1
* SMB 2 (supports dialects SMB 2.x and SMB 3.x)

**Comment by picatz** [comment]
Cool! 🎉

**Comment by sdaubert** [comment]
@KINGSABRI #74 adds support for base SMB protocol. Packetgen now may decode/encode SMBv1 base messages (ie Close, Trans, Echo, Negotiate and NtCreateAndX). But some of this messages support subprotocols, and this subprotocols are deep! Have you a specific need on SMB messages? This would help me in navigating in SMB specification.

**Comment by sdaubert** [comment]
@KINGSABRI SMB is a big big big protocol. I think it deserves a gem for itself. And, as PacketGen has a plugin mechanism, I think i will make a SMB plugin for packetgen.
I will test that this week.

**Comment by KINGSABRI** [comment]
@sdaubert great idea!, why not! 
PacketGen big and well written and extendable. Having separate gems for it is really elegant.
