### ISSUE TITLE
Add Link-Local Multicast Name Resolution (LLMNR) header.

### ISSUE THREAD

**Issue by picatz** [sdaubert/packetgen#79]
Adding support for [LLMNR](https://en.wikipedia.org/wiki/Link-Local_Multicast_Name_Resolution) could be nice to have in the future. 👍

**Comment by sdaubert** [comment]
@picatz This one will probably be moved to SMB plugin. Any objection?

**Comment by picatz** [comment]
@sdaubert I think that should work, though I'm pretty sure LLMR might not only deal with SMB traffic?

I'm not sure if it should be its own plugin. However, I do not have any strong objections to moving this to the SMB plugin, especially if it makes it easier on you. 🙇

**Comment by sdaubert** [comment]
As i have read, LLMNR is a Microsoft protocol, mainly used by windows. This is why i proposed to put it in SMB plugin.

**Comment by picatz** [comment]
@sdaubert Sounds good to me. 👍
