### ISSUE TITLE
Add Dropbox LAN Sync Discovery (DB-LSP-DISC) header

### ISSUE THREAD

**Issue by picatz** [sdaubert/packetgen#82]
The [Dropbox LAN Sync Discovery Protocol (DB-LSP-DISC)](https://www.dropbox.com/help/syncing-uploads/lan-sync-overview) would be nice to have in the future.

While I haven't done this yet, I think it would be pretty trivial to implement since it just  seems to just be a typical UDP communication on port `17500` with a JSON payload (plaintext).

**Comment by sdaubert** [comment]
@picatz what will be the interest of adding this protocol over using:

1. packetgen to capture/build UDP packets on port 17500,
2. a json library to parse/build JSON structure?

**Comment by picatz** [comment]
@sdaubert I like using PacketGen to help get an idea of the kind of traffic on a network. It's practically my favorite packet analyzer!

If I didn't know this was Dropbox, I would have to go through "the trouble" to figure it out. 

Wireshark supports this protocol, which was how I initially figured out what it was. However, I like doing all of my network-related reconnoissance on the command-line with PacketGen.

**Comment by picatz** [comment]
@sdaubert To follow up with you some more on this topic, I believe this protocol would be best suited as a plugin.

**Comment by sdaubert** [comment]
@picatz yes, i think so :smiley:
