### ISSUE TITLE
Add Discovery and Launch (DIAL) header

### ISSUE THREAD

**Issue by picatz** [sdaubert/packetgen#83]
The [DIAL](http://www.dial-multiscreen.org/home) (Discovery and Launch) protocol would be an interesting protocol to support in the future. 👍

Not sure how easy or hard it would be. [According to Wikipedia](https://en.wikipedia.org/wiki/Discovery_and_Launch) is utilizes [UPnP](https://en.wikipedia.org/wiki/Universal_Plug_and_Play), [SSDP](https://en.wikipedia.org/wiki/Simple_Service_Discovery_Protocol) and [HTTP](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol) protocols.

**Comment by sdaubert** [comment]
This is a protocol stack. Packetgen is only able to handle individual protocols.

UPnP is itself a protocol stack build on SSDP and SOAP (and maybe even others protocols).

SSDP is a text protocol over HTTP, and, although HTTP is supported by Packetgen (thanks to you @picatz), I still think Packetgen is not the good framework to handle text protocols.

Thanks @pictaz for your interest on packetgen, but I reject this issue.

**Comment by picatz** [comment]
@sdaubert No worries, thank you for looking at this issue! I appreciate the clarification on the issue of DIAL being a protocol stack. 🙇
