### ISSUE TITLE
Make Gitbook based Wiki

### ISSUE THREAD

**Issue by KINGSABRI** [sdaubert/packetgen#84]
Hello @sdaubert 

As PacketGet is getting more awesome, the wiki is not synced with the lib.

You can create a repository like "packetgen_docs" and connect [Gitbook](http://gitbook.com) to it so people either can PR to the wiki on github (it will be synced with gitbook once merged) or, you can add people you trust as writers to the gitbook space or both

What do you think?

**Comment by picatz** [comment]
I really like Gitbook. 👍

**Comment by sdaubert** [comment]
@KINGSABRI There is already a git repo for wiki at https://github.com/sdaubert/packetgen-wiki to handle github wiki. People may already PR to it, or I alreay may add people as contributors. What Gitbook will give more? I don't known it, so I hesitate to learn how to use a new tool.

**Comment by KINGSABRI** [comment]
@sdaubert 
> There is already a git repo for wiki at https://github.com/sdaubert/packetgen-wiki to handle github wiki.

Exactly, you connect this repository to gitbook and it will be bi-directional synced whether you accept PR on github or add a `writers` to gitbook to write without PR but with version control on gitbook(will be synced with github too).

> What Gitbook will give more?

Will give a great presentation and well organized documentation for PacketGen, I don't know about your vesion about this library but I look at it as the best Packet manipulation library for Ruby, even better than Packetfu which was some sort of hope to be close to Scapy but it didn't. 

> so I hesitate to learn how to use a new tool.

There's no learning curve at all. And, I'll ready to take this initiative if you like this. All I need to add me(and anyone you like, @picatz might like that, I dont know) as collaborator and I can create a space on gitbook and start enhance and collaborate easly elegancly. 

Later, I could contribute with a domain for PacketGen and bind it to gitbook page, belive me this gem deserve that.

**Comment by sdaubert** [comment]
> I don't know about your vision about this library but I look at it as the best Packet manipulation library for Ruby, even better than Packetfu which was some sort of hope to be close to Scapy but it didn't.

Thanks a lot :smiley:

**Comment by sdaubert** [comment]
@KINGSABRI 

> And, I'm ready to take this initiative if you like this. All I need to add me(and anyone you like, bro @picatz might like that, I don't know) as a collaborator and I can create a space on gitbook and start to enhance and collaborate easily and elegantly.

Ok. Add you as a collaborator to packetgen-wiki?

**Comment by KINGSABRI** [comment]
@sdaubert yes, please and I'll set this up once you give collaborator permission to write on it. Gitbook will sync with the wiki repository

**Comment by KINGSABRI** [comment]
@sdaubert the following message appears when trying to integrate the repository with gitbook
![image](https://user-images.githubusercontent.com/1071827/41998635-e47cadf6-7a63-11e8-828c-634eef1a8b4b.png)

I need administrative writes on it

**Comment by picatz** [comment]
@KINGSABRI Could you make a fork of packetgen and keep an up-to-date version of it for the GitBook synchronization?

This may require a bit more setup, but it would be a work around if @sdaubert doesn't want to give you ( or even myself for that matter ) administrative rights (read/write I guess?) at this point in time to PacketGen. I'm cool with it personally, don't get me wrong of course. Just trying to provide a potential solution to this problem at the moment until @sdaubert responds I suppose. 👍 

I also just like commenting in this repo because it's fun I guess 🤷‍♂️

**Comment by sdaubert** [comment]
@KINGSABRI I cannot set you others permissions than push one. Maybe because this is a personnal repo...

I will have a look at gitbook tonight.

**Comment by sdaubert** [comment]
Gitbook asks me my phone number to "confirm" my account. Furthermore, it seems they do not respect their privacy statement (as phone number is not cited in, and you have to record a phone number to process).

No way for me to open an account there :angry:

**Comment by picatz** [comment]
@sdaubert Thanks for trying though! 😅 🙏 

@KINGSABRI I guess the fork option might have to do? 🤔

**Comment by KINGSABRI** [comment]
> No way for me to open an account there

LOL, I never faced this, I believe you can register with **Github** account or **Google** account, have you tried that?

If @picatz suggestion suits you, I'll do it and add you to the fork as a collaborator.

**Comment by sdaubert** [comment]
I tried with my github account (and without) and a phone number is needed... And no google account for me: i am trying to keep control of my personnal data.

@KINGSABRI no problem about @picatz suggestion.

**Comment by KINGSABRI** [comment]
@sdaubert @picatz I've added you both as collaborators on my fork (restructured for gitbook)

@sdaubert look at that (https://packetgen.gitbook.io/wiki/) editing this from gitbook so elegant. 

I beilve all protocols has to has use cases to make it really elegant
