### ISSUE TITLE
Packet#to_w calculates all calculatable fields before sending.

### ISSUE THREAD

**Issue by sdaubert** [sdaubert/packetgen#97]
In current version, user has to explicitly call Packet#calc before sending a packet to send a well-formed packet. This is not done automatically to allow user to send malformed packets on wire.

But, in real life, users want to send well-formed packet more often than bad-formed ones.

In future v3.0.0 of PacketGen, Packet#calc will be automatically called, unless user explicitly forbids it.

**Comment by picatz** [comment]
@sdaubert Awesome!

I appreciate this being taken care of for me, since it's something I often end up forgetting to do myself.

**Comment by sdaubert** [comment]
Closed by 132ad40.
